#!/usr/bin/with-contenv sh

# Init config
if [ ! -f /etc/mysql/my.cnf ]; then
    mkdir -p /etc/mysql
    cp /opt/mariadb/my.cnf /etc/mysql/my.cnf
    chmod 640 /etc/mysql/my.cnf
fi

# Fix permissions of the mounted directory
chown mysql:mysql /var/lib/mysql

# Init database
if [ ! -d /var/lib/mysql/wodby ]; then
    # Generate root password
    MYSQL_ROOT_PASSWORD="$(pwgen -1 32)"
    echo $MYSQL_ROOT_PASSWORD > /var/lib/mysql/.root_password
    chmod 600 /var/lib/mysql/.root_password

    # Prepare init script
    cp /opt/mariadb/init.sql /tmp/
    sed -i 's/<<root_password>>/'"${MYSQL_ROOT_PASSWORD}"'/' /tmp/init.sql
    sed -i 's/<<wodby_password>>/'"${WODBY_DB_PASSWORD}"'/' /tmp/init.sql

    # Install database
    mysql_install_db --datadir=/var/lib/mysql
    mysqld --init-file=/tmp/init.sql >/dev/null 2>&1 &

    # Wait until mariadb initialized
    while ! mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD status >/dev/null 2>&1; do
        sleep 1
    done

    # Shutdown mariadb
    mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD shutdown

    # Remove init script
    rm /tmp/init.sql
fi
